project:
  group: laplacian-arch
  name: architecture-document-template
  type: template
  namespace: laplacian-arch
  version: '1.0.0'
  description: |
    This template generates a set of documentation of the system architecture defined by the  model.
  source_repository:
    url: https://github.com/nabla-squared/laplacian-arch.architecture-document-template.git
    branch: master
