project:
  group: laplacian-arch
  name: application-model.project-template
  type: template
  namespace: laplacian-arch
  version: '1.0.0'
  description:
    en: |
      A project template for application model development projects.
    ja: |
      このテンプレートはアプリケーションモデル開発プロジェクト用のテンプレートです。
    zh: |
      应用功能模型开发项目的项目模板。
  source_repository:
    url: https://github.com/laplacian-arch/application-model.project-template.git
    branch: master
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  template_files:
  - 'dest/template'
