project:
  group: laplacian-arch
  name: arch-model.project-template
  type: template
  namespace: laplacian-arch
  version: '1.0.0'
  description:
    en: |
      This template generates a set of documentation of the system architecture defined by the  model.
    ja: |
      This template generates a set of documentation of the system architecture defined by the  model.
    zh: |
      This template generates a set of documentation of the system architecture defined by the  model.
  source_repository:
    url: https://github.com/laplacian-arch/arch-model.project-template.git
    branch: master
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
