project:
  sources:
  - "README.md"
  - ".editorconfig"
  - ".gitattributes"
  - ".gitignore"
  - "model/project/scripts/generate.yaml"
  - "model/project/scripts/publish-local.yaml"
  - "model/project/sources.yaml"
  - "model/project.yaml"
  - "src/doc/architecture-overview.md"
  - "src/doc/image/component-diagram.puml.hbs"
  - "src/doc/local-deployment.md"
  - "src/model/project/document/architecture-model.yaml"
  - "src/model/project/document/{each datasources as datasource}{hyphen datasource.name}.hbs.yaml"
